name: Meu Primeiro Workflow no GitHub Actions

on: 
  push:
    branches: [ "main" ]
    
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  job01:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Olá, turma da disciplina GitHub Actions.

